language: python
python:
  - "3.5"
before_install:
    - sudo add-apt-repository -y ppa:pylab/stable
    - sudo apt-get update -qq
    - sudo apt-get install -qq python3-numpy python3-scipy python3-nose2
script: nose2
